if(false){ const sports=[['⚽','Football'],['🎾','Tennis'],['🏀','Basket'],['🏎️','F1'],['🏉','Rugby'],['🥊','MMA'],['🥊','Boxe'],['🏒','Hockey'],['🏐','Volley'],['🤾','Handball'],['⚾','Baseball'],['⛳','Golf'],['🚴','Cyclisme'],['🎯','Fléchettes'],['🎮','eSports']];
document.getElementById('sports').innerHTML=sports.map((s,i)=>`<button data-sport="${s[1]}" class="${i===0?'active':''}"><span class="ico">${s[0]}</span>${s[1]}</button>`).join('');
document.querySelectorAll('#sports button').forEach(b=>b.addEventListener('click', async()=>{document.querySelectorAll('#sports button').forEach(x=>x.classList.remove('active'));b.classList.add('active'); try { await loadRealScores(); } catch(e) { document.getElementById('dataSource').textContent='Mode démonstration · API indisponible'; }}));
const live=[['Angleterre · Premier League','67′','Liverpool','2','Fulham','0'],['Angleterre · Premier League','54′','Man. City','1','Brentford','1'],['Espagne · LaLiga','54′','Real Madrid','1','Real Sociedad','1'],['Italie · Serie A','23′','Inter','0','Juventus','0'],['France · Ligue 1','38′','PSG','2','Lens','1'],['Allemagne · Bundesliga','12′','Bayern','0','Dortmund','0']];
document.getElementById('matches').innerHTML=live.map((m,i)=>`${i===0||live[i-1][0]!==m[0]?`<div class="league">${m[0]}</div>`:''}<div class="match"><div class="time">${m[1]}</div><div class="team">${m[2]}</div><div class="score">${m[3]}</div><div class="team">${m[4]}</div><div><b>${m[5]}</b><div class="live">LIVE</div></div></div>`).join('');
const upcoming=[['20:45','PSG','Lens'],['21:00','Barcelona','Girona'],['21:00','Milan','Napoli'],['21:15','OM','Lyon']];document.getElementById('upcoming').innerHTML=upcoming.map(x=>`<div class="up"><b>${x[0]}</b><span>${x[1]}</span><span>vs ${x[2]}</span><span>☆</span></div>`).join('');
const popular=[['Liverpool gagne',78],['+2.5 buts · Real Madrid',72],['PSG gagne',68],['Les deux marquent · Inter',65]];document.getElementById('popular').innerHTML=popular.map(x=>`<div class="pick"><span>${x[0]}</span><b>${x[1]}%</b></div><div class="bar"><i style="width:${x[1]}%"></i></div>`).join('');
const preds=[['Liverpool','Fulham','1.45'],['Real Madrid','Real Sociedad','1.60'],['PSG','Lens','1.30'],['Bayern','Dortmund','1.55']];document.getElementById('predictionList').innerHTML=preds.map(x=>`<div class="prediction"><b>${x[0]} <span style="color:#758078">vs</span> ${x[1]}</b><p>Choisissez votre pronostic et gagnez des points virtuels.</p><div class="choices"><button onclick="vote(this)">1 · ${x[2]}</button><button onclick="vote(this)">X</button><button onclick="vote(this)">2</button></div></div>`).join('');
const ranks=['Alexinho','Hakim','LeCoach','FootPassion','NeymarDz','Roro7','Zizo','Mika93','Tactix','Ben10'];document.getElementById('rankingList').innerHTML=ranks.map((n,i)=>`<div class="rank"><strong>#${i+1}</strong><span>${n}</span><b>${2450-i*130} pts</b></div>`).join('');
function show(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.bottom button').forEach(b=>b.classList.remove('active'));const map={home:0,predictions:2,rankings:3,profile:4};if(map[id]!=null)document.querySelectorAll('.bottom button')[map[id]].classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}function vote(btn){btn.style.background='var(--green)';btn.style.color='#061006';btn.textContent+=' ✓'}

}

